language: python
env:
  - PYTHON_VERSION="3.5"
# command to install dependencies
os:
  - linux
 
install:
  # Install conda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update --yes conda
  - conda create --yes -n ci "python=$PYTHON_VERSION"
  - source activate ci
  - which python
  - which pip
  - python --version
  - pip --version
  # command to install dependencies
  - pip install coveralls
  - pip install flake8
  - pip install nose
  - pip install pandas
  - pip install boto3
# command to run tests
script:
  - echo "Run script here"
after_success:
  - git config user.email "travis@travis.org"
  - git config user.name "travis"
  - git pull
  - cd data
  - rm Readme.md
  - python files_counter.py
  - cat test.md
  - git add test.md
  - git commit --allow-empty -m "updated README.md"
  - git push https://pshivraj:$GITHUB_API_KEY@github.com/pshivraj/cetus HEAD:master
  - echo "Finished"
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ] ; then echo "Run prediction script weekly" ; fi
  - if [ "$TRAVIS_EVENT_TYPE" != "cron" ] ; then echo "Non cron job process" ; fi
